#!/bin/bash
sort -t, -k3,3nr /lab-1_Group-25/raw_data/satelite_temperature_data.csv| head -n 10 > /lab-1_Group-25/analyzed_data/highest_temp.csv
echo "Done with the Temperature"
grep "Kenya" /lab-1_Group-25/raw_data/satelite_temperature_data.csv | sort -t, -k4,4nr > /lab-1_Group-25/analyzed_data/humidity_data_Kenya.csv
echo "Done Sorting acording to humidity"
